name = "rosa-jewelry"
main = "worker.js"
compatibility_date = "2025-05-01"

assets = { directory = "public", binding = "ASSETS" }

[[kv_namespaces]]
binding = "ROSA_DB"
id = "ea5150dc4c9f49ad86e489d044cb9939"
